Deployment com GitHub Pages
ufrpe-devs/ufrpe-devs.github.io pull request #1
Opened 2021-08-31 19:09 UTC by SteffanoP

## Descrição Rápida

Por meio dessa Pull Request é possível realizar o deployment através da ferramenta de hospedagem de site do GitHub Pages

## Como funciona?

É criado um workflow apelidado de [Deploy to GitHub Pages](https://github.com/SteffanoP/ufrpe-devs.github.io/actions/workflows/deploy.yml), esse workflow realiza o deployment sempre que é enviado um commit para a branch `main`. Este workflow funciona por meio da Action [peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages) que realiza o deployment para a branch `gh-pages`

## Desvantagens

Não é possível utilizar rotas de API, tal como nada de forma dinâmica, porém há ressalvas do que se possa ser realizado.

## Referência

[Next.js Github Pages](https://gregrickaby.com/blog/nextjs-github-pages)

2021-08-31 19:15 UTC, SteffanoP commented
@ItaloSa estou tendo o seguinte problema no desenvolvimento dessa PR:

```log
Error: Image Optimization using Next.js' default loader is not compatible with `next export`.
  Possible solutions:
    - Use `next start` to run a server, which includes the Image Optimization API.
    - Use any provider which supports Image Optimization (like Vercel).
    - Configure a third-party loader in `next.config.js`.
    - Use the `loader` prop for `next/image`.
  Read more: https://nextjs.org/docs/messages/export-image-api
    at /home/runner/work/ufrpe-devs.github.io/ufrpe-devs.github.io/node_modules/next/dist/export/index.js:257:23
    at async Span.traceAsyncFn (/home/runner/work/ufrpe-devs.github.io/ufrpe-devs.github.io/node_modules/next/dist/telemetry/trace/trace.js:60:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Esse erro acontece pois há um problema quando geramos o site estático, pois a API de Otimização de Imagem não funciona com o comando `next export` que é o comando que exporta o site estático. Dessa forma há as seguintes ressalvas:

- Configure a third-party loader in `next.config.js`.

É possível por meio do seguinte pacote: [cyrilwanner/next-optimized-images](https://github.com/cyrilwanner/next-optimized-images)

- Use the `loader` prop for `next/image`.

Já com o loader seria o seguinte: https://nextjs.org/docs/api-reference/next/image#loader

Daí te pergunto, qual seria a melhor forma para o que queremos?

2021-09-01 01:58 UTC, ItaloSa commented
Acho que de início vamos ignorar isso enquanto ainda não temos imagens. Vou fazer um commit com o setup do chakra daí acho que resolve isso.

2021-09-01 02:03 UTC, SteffanoP commented
> Acho que de início vamos ignorar isso enquanto ainda não temos imagens. Vou fazer um commit com o setup do chakra daí acho que resolve isso.

Beleza, fico no aguardo das novas alterações e atualizo a branch quando estiver pronto!

2021-09-01 02:58 UTC, SteffanoP commented
@ItaloSa pronto pra revisão, se quiser ver a action funcionando dá uma olhada na minha fork e também no deployment.

Fork - https://github.com/SteffanoP/ufrpe-devs.github.io
Deployment - https://steffanop.github.io/ufrpe-devs.github.io/

2021-09-01 12:37 UTC, ItaloSa requested changes
Só ajustar um pequeno detalhe

2021-09-01 12:37 UTC, ItaloSa commented on .github/workflows/deploy.yml
> +  build:
```suggestion
  # This workflow contains a single job called "deploy"
  deploy:
```

2021-09-01 13:25 UTC, merged