Feature/site top
ufrpe-devs/ufrpe-devs.github.io pull request #8
Opened 2021-09-18 03:30 UTC by ThalesGabriel

2021-09-18 03:33 UTC, SteffanoP requested changes
A implementação está ótima, segue bem a ideia do Figma, só queria pedir pra tu ajustar esse espaço entre a descrição e a imagem.

![image](https://user-images.githubusercontent.com/26782009/133871126-63bb9a16-8617-4b1a-b639-0ba1d3d9d955.png)

Eu creio que acaba ficando muito próximo, não sei ao certo, mas acho que deveria ter um espaçamento ali.

2021-09-18 03:34 UTC, SteffanoP reviewed
Outra coisa que notei, que não sei bem como é tal prioridade agora, mas o layout para celular tá um pouco quebrado

![image](https://user-images.githubusercontent.com/26782009/133871249-e49af4bd-5ba0-4b21-b901-2b01175a7626.png)

2021-09-18 16:54 UTC, ItaloSa requested changes
Muito bom! Mas precisamos ver alguns pontos aí

2021-09-18 16:54 UTC, ItaloSa commented on components/Home/components/Hero/index.jsx
> +        <Button bg="#00AAFC" color="white" id="hero-community-button-2">Community</Button>
Não sei se ja fizeste o rebase com a master, mas essa cor do bg o ideal é que venha do tema.

2021-09-18 16:54 UTC, ItaloSa commented on components/Page/components/Navbar/index.jsx
> +      {/* <Box bg={useColorModeValue('gray.100', 'gray.900')} px={4}> */}
E esse comentário aqui?

2021-09-18 16:54 UTC, ItaloSa commented on components/Page/components/Navbar/index.jsx
> +  }, [isTinyThan767])
Isso aqui ta estranho kkk. Tem que ter algum jeito sem ser pelo document...

2021-09-18 16:54 UTC, ItaloSa commented on components/Page/components/Navbar/index.jsx
> +            </Button> */}
Vamos evitar coisas comentadas

2021-09-18 16:54 UTC, ItaloSa commented on components/Page/components/Navbar/index.jsx
> +      {/* <Box p={4}>Main Content Here</Box> */}
same here

2021-09-18 16:54 UTC, ItaloSa commented on styles/theme.js
> +      "#main-logo-rectangle": {
hummm... não sei hein. Não curti isso aqui tão centralizado.... talvez seja melhor usar o styled mesmo ou arrumar uma forma de fazer isso mais próximo do componente

2021-09-24 18:58 UTC, adrcav approved these changes
LGTM! =)

2021-09-24 18:59 UTC, ItaloSa approved these changes

2021-09-24 22:51 UTC, SteffanoP approved these changes

2021-09-24 23:35 UTC, merged